---
# https://taskfile.dev
version: '3'

tasks:
  init:
    cmds:
      - go mod tidy
  assets:
    desc: Build the assets
    cmds:
      - bunx tailwindcss -i ./static/css/tailwind.css -o ./static/css/global.css
  generate:
    desc: Generate templates
    cmds:
      - templ generate
  run:
    desc: Run the application
    deps:
      - assets
      - generate
    cmds:
      - go run ./cmd/server/...

