// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const getLatestMetrics = `-- name: GetLatestMetrics :one
SELECT 
    DATE(timestamp) as date,
    SUM(keypresses) as total_keypresses,
    SUM(mouse_clicks) as total_mouse_clicks,
    CAST(SUM(mouse_distance_in) AS DOUBLE PRECISION) as total_mouse_travel_in,
    CAST(SUM(mouse_distance_mi) AS DOUBLE PRECISION) as total_mouse_travel_mi,
    SUM(scroll_steps) as total_scroll_steps
FROM metrics
WHERE DATE(timestamp) = (
    SELECT DATE(timestamp)
    FROM metrics
    ORDER BY timestamp DESC
    LIMIT 1
)
GROUP BY DATE(timestamp)
`

type GetLatestMetricsRow struct {
	Date               time.Time
	TotalKeypresses    int64
	TotalMouseClicks   int64
	TotalMouseTravelIn float64
	TotalMouseTravelMi float64
	TotalScrollSteps   int64
}

func (q *Queries) GetLatestMetrics(ctx context.Context) (GetLatestMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestMetrics)
	var i GetLatestMetricsRow
	err := row.Scan(
		&i.Date,
		&i.TotalKeypresses,
		&i.TotalMouseClicks,
		&i.TotalMouseTravelIn,
		&i.TotalMouseTravelMi,
		&i.TotalScrollSteps,
	)
	return i, err
}
